Update package.json to remove terra-markdown
cerner/terra-ui pull request #312
Opened 2020-11-05 22:35 UTC by ryanthemanuel

### Summary

Update package.json to remove terra-markdown\

2020-11-05 22:52 UTC, emilyrohrbough approved these changes

2020-11-05 23:39 UTC, StephenEsser approved these changes

2020-11-06 00:10 UTC, mjhenkes requested changes
Terra-markdown must still be pulled in transitively, it's still on the doc site.

2020-11-07 19:37 UTC, mjhenkes approved these changes
i added the exclude to terra-dev-site config

2020-11-07 19:37 UTC, merged