Add @cerner/terra-toolkit-docs to terra-ui
cerner/terra-ui pull request #324
Opened 2020-12-16 21:21 UTC by StephenEsser

### Summary

This PR adds the @cerner/terra-toolkit-docs dev site documentation pages to terra-ui.

Thank you for contributing to Terra.
@cerner/terra

2020-12-16 23:50 UTC, emilyrohrbough approved these changes

2020-12-16 23:55 UTC, benbcai approved these changes

2020-12-17 00:23 UTC, mjhenkes approved these changes

2020-12-17 00:29 UTC, mjhenkes requested changes
Sorry we should hold off till I can check why it failed to deploy.

2020-12-17 02:34 UTC, mjhenkes commented
This wasn't building because postcss due to pulling in both terra-toolkit's webpack config and @cerner/webpack-config-terra. I think postcss 8 was ending up at root. I think i could have fixed this by installing postcss 7 but, i took the opportunity to expand the scope by upgrading to the new webpack config and terra-cli to remove the dependency on terra-toolkit (the package).

This should not be merged until the next release of terra-toolkit (the mono repo) which will contain aggregate themes (again 🤢 ).

2021-01-05 15:58 UTC, mjhenkes approved these changes

2021-01-05 16:27 UTC, merged